img_size: [256,256]
features: 16

batch_size: 8
lr: 3.e-3
epochs: 100
warmup: 5

# ckpt: "backup/checkpoint_96"
# ckpt: "backup/checkpoint_100"

focal_loss:
  weight: 1.0

dice_bce_loss:
  weight: 1.0
